"""Waiver mechanics: validation and fail-closed blocking rules (M2, TASK-0004)."""

from __future__ import annotations

from .enforcement import (
    REASON_AGENT_MAY_NOT_APPROVE,
    REASON_AGENT_MAY_NOT_CREATE,
    REASON_APPROVER_IS_RISK_OWNER,
    REASON_APPROVER_NOT_SECURITY_REVIEWER,
    REASON_CRITICAL_NEVER_WAIVED,
    REASON_EXPIRES_BEFORE_CREATED,
    REASON_HIGH_NEVER_WAIVED,
    REASON_INVALID_WAIVER,
    REASON_SEVERITY_NOT_WAIVABLE,
    REASON_WAIVER_EXPIRED,
    REASON_WAIVER_MISSING,
    REASON_WAIVER_REVOKED,
    SECURITY_REVIEWER_ROLE,
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
    BlockDecision,
    WaiverCheck,
    check_waiver,
    evaluate_risk,
    is_waivable,
    may_manage_waiver,
    parse_timestamp,
    validate_waiver,
    waiver_state,
)

__all__ = [
    "REASON_AGENT_MAY_NOT_APPROVE",
    "REASON_AGENT_MAY_NOT_CREATE",
    "REASON_APPROVER_IS_RISK_OWNER",
    "REASON_APPROVER_NOT_SECURITY_REVIEWER",
    "REASON_CRITICAL_NEVER_WAIVED",
    "REASON_EXPIRES_BEFORE_CREATED",
    "REASON_HIGH_NEVER_WAIVED",
    "REASON_INVALID_WAIVER",
    "REASON_SEVERITY_NOT_WAIVABLE",
    "REASON_WAIVER_EXPIRED",
    "REASON_WAIVER_MISSING",
    "REASON_WAIVER_REVOKED",
    "SECURITY_REVIEWER_ROLE",
    "SEVERITY_CRITICAL",
    "SEVERITY_HIGH",
    "SEVERITY_LOW",
    "SEVERITY_MEDIUM",
    "BlockDecision",
    "WaiverCheck",
    "check_waiver",
    "evaluate_risk",
    "is_waivable",
    "may_manage_waiver",
    "parse_timestamp",
    "validate_waiver",
    "waiver_state",
]