#!/usr/bin/env bash
# User-local toolchain bootstrap for the Secure Agentic SDLC project (no sudo required).
#
# Installs baseline v1 tooling into ~/.local (binaries) and ~/.local/go (Go toolchain),
# and appends ~/.local/bin to PATH in ~/.profile and ~/.bashrc.
#
# Reproducibility: resolved versions are recorded in toolchain.lock next to this script.
# On later runs the locked versions are reused. Pass --latest to re-resolve.
#
# Usage:
#   bash infra/wsl/bootstrap-toolchain.sh          # install / repair
#   bash infra/wsl/bootstrap-toolchain.sh --check  # report only
#   bash infra/wsl/bootstrap-toolchain.sh --latest # re-resolve newest versions

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCK_FILE="${SCRIPT_DIR}/toolchain.lock"
BIN_DIR="${HOME}/.local/bin"
GO_DIR="${HOME}/.local/go"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

CHECK_ONLY=0
USE_LATEST=0
for arg in "$@"; do
  case "${arg}" in
    --check) CHECK_ONLY=1 ;;
    --latest) USE_LATEST=1 ;;
    *) echo "unknown argument: ${arg}" >&2; exit 2 ;;
  esac
done

mkdir -p "${BIN_DIR}"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }

arch() {
  case "$(uname -m)" in
    x86_64 | amd64) echo "amd64" ;;
    aarch64 | arm64) echo "arm64" ;;
    *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
  esac
}
arch_x86() {
  case "$(uname -m)" in
    x86_64 | amd64) echo "x86_64" ;;
    aarch64 | arm64) echo "aarch64" ;;
    *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
  esac
}
arch_x64() {
  case "$(uname -m)" in
    x86_64 | amd64) echo "x64" ;;
    aarch64 | arm64) echo "arm64" ;;
    *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
  esac
}

# --- lock file -----------------------------------------------------------------

declare -A LOCKED=()
load_lock() {
  [ -f "${LOCK_FILE}" ] || return 0
  while IFS='=' read -r key value; do
    [ -z "${key}" ] && continue
    case "${key}" in \#*) continue ;; esac
    LOCKED["${key}"]="${value}"
  done <"${LOCK_FILE}"
}

save_lock() {
  {
    echo "# Resolved toolchain versions. Regenerate with: bash infra/wsl/bootstrap-toolchain.sh --latest"
    echo "# Generated by bootstrap-toolchain.sh; safe to commit."
    if [ "${#LOCKED[@]}" -gt 0 ]; then
      for key in "${!LOCKED[@]}"; do printf '%s=%s\n' "${key}" "${LOCKED[${key}]}"; done | sort
    fi
  } >"${LOCK_FILE}"
  log "wrote ${LOCK_FILE}"
}

RESOLVED=""
resolve_gh() {
  local key="$1" repo="$2"
  if [ "${USE_LATEST}" -eq 0 ] && [ -n "${LOCKED[${key}]:-}" ]; then
    RESOLVED="${LOCKED[${key}]}"
    return 0
  fi
  local tag
  tag="$(curl -fsSL "https://api.github.com/repos/${repo}/releases/latest" 2>/dev/null \
    | grep -o '"tag_name": *"[^"]*"' | head -n1 | cut -d'"' -f4)"
  [ -n "${tag}" ] || { warn "could not resolve latest ${key} from ${repo}"; return 1; }
  LOCKED["${key}"]="${tag}"
  RESOLVED="${tag}"
  return 0
}

# install_gh_binary <name> <repo> <key> <asset-tpl> <mode:tar|raw>
install_gh_binary() {
  local name="$1" repo="$2" key="$3" asset_tpl="$4" mode="$5" ver
  ver=""
  resolve_gh "${key}" "${repo}" || return 0
  ver="${RESOLVED}"
  if [ -x "${BIN_DIR}/${name}" ] && [ "${USE_LATEST}" -eq 0 ]; then
    log "${name} ${ver}: already installed (${BIN_DIR}/${name})"
    return 0
  fi
  local ver_nover="${ver#v}" asset
  asset="$(printf '%s' "${asset_tpl}" \
    | sed "s/{ver}/${ver}/g; s/{ver_nover}/${ver_nover}/g; s/{arch_x86}/$(arch_x86)/g; s/{arch_x64}/$(arch_x64)/g; s/{arch}/$(arch)/g")"
  local url="https://github.com/${repo}/releases/download/${ver}/${asset}"
  log "${name} ${ver}  <- ${asset}"
  [ "${CHECK_ONLY}" -eq 1 ] && return 0

  local out="${TMP_DIR}/${name}.download"
  if ! curl -fsSL "${url}" -o "${out}"; then
    warn "${name}: download failed ${url}"
    return 0
  fi
  if [ "${mode}" = "raw" ]; then
    install -m 0755 "${out}" "${BIN_DIR}/${name}"
    return 0
  fi
  if ! tar -xzf "${out}" -C "${TMP_DIR}" 2>/dev/null; then
    warn "${name}: archive extraction failed (${asset})"
    return 0
  fi
  local found
  found="$(find "${TMP_DIR}" -maxdepth 3 -type f -name "${name}" | head -n1)"
  if [ -n "${found}" ]; then
    install -m 0755 "${found}" "${BIN_DIR}/${name}"
  else
    warn "${name}: binary not found inside archive ${asset}"
  fi
}

install_go() {
  local ver
  if [ "${USE_LATEST}" -eq 0 ] && [ -n "${LOCKED[go]:-}" ]; then
    ver="${LOCKED[go]}"
  else
    ver="$(curl -fsSL 'https://go.dev/VERSION?m=text' 2>/dev/null | head -n1)"
    [ -n "${ver}" ] || { warn "could not resolve Go version"; return 0; }
    LOCKED[go]="${ver}"
  fi
  log "go ${ver}"
  if [ "${CHECK_ONLY}" -eq 1 ]; then return 0; fi
  if [ -x "${GO_DIR}/bin/go" ] && "${GO_DIR}/bin/go" version 2>/dev/null | grep -q "${ver}"; then
    log "go ${ver}: already installed"
    return 0
  fi
  local tarball="${ver}.linux-$(arch).tar.gz"
  if curl -fsSL "https://go.dev/dl/${tarball}" -o "${TMP_DIR}/go.tar.gz"; then
    rm -rf "${GO_DIR}"
    mkdir -p "${GO_DIR}"
    tar -xzf "${TMP_DIR}/go.tar.gz" -C "${GO_DIR}" --strip-components=1
    log "go -> ${GO_DIR}/bin/go"
  else
    warn "go download failed"
  fi
}

install_uv() {
  if command -v uv >/dev/null 2>&1 || [ -x "${BIN_DIR}/uv" ]; then
    log "uv: already installed"
    return 0
  fi
  log "uv (astral)"
  [ "${CHECK_ONLY}" -eq 1 ] && return 0
  if curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="${BIN_DIR}" sh >/dev/null 2>&1; then
    log "uv installed -> ${BIN_DIR}/uv"
  else
    warn "uv install failed"
  fi
}

install_semgrep() {
  if command -v semgrep >/dev/null 2>&1 || [ -x "${BIN_DIR}/semgrep" ]; then
    log "semgrep: already installed"
    return 0
  fi
  log "semgrep"
  [ "${CHECK_ONLY}" -eq 1 ] && return 0
  if [ -x "${BIN_DIR}/uv" ]; then
    if "${BIN_DIR}/uv" tool install semgrep >/dev/null 2>&1; then
      log "semgrep installed via uv -> ${BIN_DIR}/semgrep"
      return 0
    fi
    warn "uv tool install semgrep failed"
  fi
  local venv="${HOME}/.local/share/semgrep-venv"
  if [ ! -x "${venv}/bin/pip" ]; then
    if ! python3 -m venv "${venv}" 2>/dev/null; then
      warn "cannot create venv (ensurepip/python3-venv missing)."
      warn "  fix with: sudo apt update && sudo apt install -y python3-venv"
      return 0
    fi
  fi
  if "${venv}/bin/pip" install --quiet semgrep; then
    ln -sf "${venv}/bin/semgrep" "${BIN_DIR}/semgrep"
    log "semgrep installed -> ${BIN_DIR}/semgrep"
  else
    warn "semgrep install failed"
  fi
}

ensure_path() {
  local line='export PATH="$HOME/.local/bin:$HOME/.local/go/bin:$PATH"'
  for rc in "${HOME}/.profile" "${HOME}/.bashrc"; do
    [ -f "${rc}" ] || touch "${rc}"
    grep -qF '.local/go/bin' "${rc}" || printf '\n# Secure Agentic SDLC toolchain\n%s\n' "${line}" >>"${rc}"
  done
}

# --- run -----------------------------------------------------------------------

load_lock
log "arch=$(arch)  bin=${BIN_DIR}  check_only=${CHECK_ONLY}  latest=${USE_LATEST}"

install_go
install_gh_binary opa      open-policy-agent/opa  opa      "opa_linux_{arch}_static"        raw
install_gh_binary gh       cli/cli                gh       "gh_{ver_nover}_linux_{arch}.tar.gz" tar
install_gh_binary cosign   sigstore/cosign        cosign   "cosign-linux-{arch}"            raw
install_gh_binary syft     anchore/syft           syft     "syft_{ver_nover}_linux_{arch}.tar.gz" tar
install_gh_binary trivy    aquasecurity/trivy     trivy    "trivy_{ver_nover}_Linux-64bit.tar.gz" tar
install_gh_binary gitleaks gitleaks/gitleaks      gitleaks "gitleaks_{ver_nover}_linux_{arch_x64}.tar.gz" tar
install_gh_binary buf      bufbuild/buf           buf      "buf-Linux-{arch_x86}"           raw
install_uv
install_semgrep

# Record installed versions of tools not resolved from GitHub releases.
if [ -x "${BIN_DIR}/uv" ]; then LOCKED[uv]="$("${BIN_DIR}/uv" --version 2>/dev/null | awk '{print $2}')"; fi
if [ -x "${BIN_DIR}/semgrep" ]; then LOCKED[semgrep]="$("${BIN_DIR}/semgrep" --version 2>/dev/null | head -n1)"; fi

if [ "${CHECK_ONLY}" -eq 0 ]; then
  ensure_path
  save_lock
fi

log "done. Open a new shell (or 'source ~/.profile') so PATH picks up ${BIN_DIR}."
